# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and push maven images

on: 
  workflow_call:
    secrets:
      nexus_user:
        required: true
        description: User to login into Nexus
      nexus_password:
        required: true
        description: Password to login into Nexus
      docker_nexus_token:
        required: true
        description: Token to login into Docker Nexus
      docker_nexus_username:
        required: true
        description: User name to login into Docker Nexus
    inputs:
      nexus_url:
        required: true
        description: URL of Nexus
        type: string
      image_name:
        required: true
        description: Name of the image to build
        type: string
      java_version:
        required: true
        description: Java version to use
        type: string

   
jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get branch name
      uses: nelonoel/branch-name@v1.0.1

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'adopt'
        cache: maven
        
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v18
      with: 
        servers: >
          [
            {
              "id": "anemone-nexus-releases",
              "username": "${{ secrets.nexus_user }}",
              "password": "${{ secrets.nexus_password }}"
            },
            {
              "id": "anemone-nexus-public",
              "username": "${{ secrets.nexus_user }}",
              "password": "${{ secrets.nexus_password }}"
            },
            {
              "id": "anemone-nexus-central",
              "username": "${{ secrets.nexus_user }}",
              "password": "${{ secrets.nexus_password }}"
            },
            {
              "id": "anemone-nexus-snapshots",
              "username": "${{ secrets.nexus_user }}",
              "password": "${{ secrets.nexus_password }}"
            }
          ]
          
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Nexus
      uses: docker/login-action@v1 
      with:
        registry: ${{ inputs.nexus_url }}
        username: ${{ secrets.docker_nexus_username }}
        password: ${{ secrets.docker_nexus_token }}
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/syltek/${{ inputs.image_name }}
        tags: |
          type=ref,event=branch,suffix=-{{date 'YYYYMMDDHHmmss'}}-{{sha}}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: YAML Update Action
      uses: fjogeleit/yaml-update-action@v0.6.1
      with:
        valueFile: 'deploy/develop/kustomization.yaml'
        propertyPath: 'images[0].newTag'
        value: ${{ steps.meta.outputs.tags[0] }}
        commitChange: true
        branch: develop
        createPR: false
        updateFile: true
        message: 'Update image tag'